#+title: Welcome to /mblognl/
#+author: mbrignall
#+date: <2024-10-03>
#+TODO: TODO STARTED | DONE

* ...a blog you say? @@html:<i class="fa-regular fa-circle-question"></i>@@

I use this space so I can personally revisit items of interest, store knowledge and maybe achievements.

** What to expect

You'll likely find me talking about my favourite technologies. I may, from time to time, speak of other interests. I may even cover topics that overlap with creative and otherworldly interests.

I hope you find something useful or thought-provoking!

Some topics, themes, and subjects:

- *Cybersecurity and Security Engineering*
- *Web Development and Web Design*
- *Talking lovingly about Emacs*
- *Experiments, code snippets and projects*
- *Single Board Computer exploration*

* Current Book(s) @@html:<i class="fa-solid fa-book"></i>@@

On rotation this month:

** To Anyone Who Ever Asks: The Life, Music, and Mystery of Connie Converse :music:folklore:

| Author           | Howard Fishman |
| Publication date |     2024-05-02 |

https://m.media-amazon.com/images/I/616XekvMCTL._AC_UF894,1000_QL80_.jpg

So far this book is awesome and intriguing. I have only read the first few chapters and listened to her music for sometime, but hadn't been aware of her strange career.


@@html:<div style="clear: both;"></div>@@

* Previous Books @@html:<i class="fa-solid fa-book"></i>@@

Ongoing reads/ last completed book:

** Code: The Hidden Language of Computer Hardware and Software :computer:science:technology:

| Author           | Charles Petzold |
| Publication date |      1999-09-29 |

https://m.media-amazon.com/images/I/61Hc-9h+-XL.jpg

I am half way through this book so far, it's fascinating. Covering the beginning of code/bits/bytes up to modern computing. It has illuminated some points of computing that I have not covered for some time. More on that soon.

I think I hit a bit of a roof on this one when it started to get super techincal, I decided to take the second half a bit slower.

In Progress... Still in progress.

[[./books.html][Read More...]]


@@html:<div style="clear: both;"></div>@@

* Contact @@html:<i class="fa-solid fa-house"></i>@@

Feel free to reach out via email or GitHub:

| [[mailto:hello@mbrig.nl][email me]]         | @@html:<i class="fa fa-envelope"></i>@@          |
| [[https://github.com/mbrignall][github/mbrignall]] | @@html:<i class="fa-brands fa-github-alt"></i>@@ |

* Post Archive @@html:<i class="fa-solid fa-box-archive"></i>@@

[[file:archive.org][All Posts]]
