#+title: Welcome to /mblognl/
#+author: mbrignall
#+date: <2024-10-03>
#+TODO: TODO STARTED | DONE

* ...a blog you say?

I use this space so I can personally revisit items of interest, store knowledge and maybe achievements.

** What to expect

You'll likely find me talking about my favourite technologies. I may, from time to time, speak of other interests. I may even cover topics that overlap with creative and otherworldly interests.

I hope you find something useful or thought-provoking!

Some topics, themes, and subjects:

- *Cybersecurity and Security Engineering*
- *Web Development and Web Design*
- *Talking lovingly about Emacs*
- *Experiments, code snippets and projects*
- *Single Board Computer exploration*

* Current Book(s)

On rotation this month:

** How Bluegrass Music Destroyed My Life

| Author           | John Fahey |
| Publication date | 24-04-2010 |

https://m.media-amazon.com/images/I/712DzUtij-L._AC_UF894,1000_QL80_.jpg

Second time reading. Love this book - collection of short stories written by the legend himself.

* Previous Books

Ongoing reads/ last completed book:

** Enshittification: Why Everything Suddenly Got Worse and What To Do About It

| Author           | Cory Doctorow |
| Publication date | 14/10/2025    |

Terrifying at times, and very informative. If you want to know how the world became enshittified then get the book (or audio book read by the author)

[[./books.html][Read More...]]

* Contact

Feel free to reach out via email or GitHub:

| @@html:<i class="fa fa-envelope"></i>@@          | [[mailto:hello@mbrig.nl][email me]]         |
| @@html:<i class="fa-brands fa-github-alt"></i>@@ | [[https://github.com/mbrignall][github/mbrignall]] |

* Post Archive

[[file:archive.org][All Posts]]
